# Generated by Django 3.1 on 2020-10-04 20:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio3science', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectXUniversityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio3science.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectXUniversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio3science.project')),
                ('project_x_university_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio3science.projectxuniversitytype')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio3science.university')),
            ],
            options={
                'unique_together': {('project', 'university', 'project_x_university_type')},
            },
        ),
        migrations.CreateModel(
            name='ProjectXCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio3science.community')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio3science.project')),
            ],
            options={
                'unique_together': {('project', 'community')},
            },
        ),
    ]
