# Generated by Django 3.1 on 2020-08-25 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio3science', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
